type RuntimeEnv = Record<string, string | undefined>
type RuntimeGlobal = typeof globalThis & {
	__env__?: RuntimeEnv
	env?: RuntimeEnv
}

const buildTimeEnv: RuntimeEnv = {
	CF_PAGES_URL: process.env.CF_PAGES_URL,
	AUTH_URL: process.env.AUTH_URL,
	AUTH_SECRET: process.env.AUTH_SECRET,
	NEXTAUTH_URL: process.env.NEXTAUTH_URL,
	NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
	AUTH_BACKEND_API_URL: process.env.AUTH_BACKEND_API_URL,
	BACKEND_API_URL: process.env.BACKEND_API_URL,
	NEXT_PUBLIC_BACKEND_API_URL: process.env.NEXT_PUBLIC_BACKEND_API_URL,
	NEXT_PUBLIC_TACHYON_API_URL: process.env.NEXT_PUBLIC_TACHYON_API_URL,
	NEXT_PUBLIC_PLATFORM_ID: process.env.NEXT_PUBLIC_PLATFORM_ID,
	TACHYON_FIELD_API_URL: process.env.TACHYON_FIELD_API_URL,
	TACHYON_API_URL: process.env.TACHYON_API_URL,
	TACHYON_FIELD_EXTENSION_REGISTRY_STUB:
		process.env.TACHYON_FIELD_EXTENSION_REGISTRY_STUB,
	TACHYON_FIELD_EXTENSION_REGISTRY_STUB_APPS:
		process.env.TACHYON_FIELD_EXTENSION_REGISTRY_STUB_APPS,
	TACHYON_FIELD_GOLF_EXTENSION_URL:
		process.env.TACHYON_FIELD_GOLF_EXTENSION_URL,
	TACHYON_FIELD_RESTAURANT_EXTENSION_URL:
		process.env.TACHYON_FIELD_RESTAURANT_EXTENSION_URL,
	VITE_PHOTON_DEPLOYMENT_MODE: process.env.VITE_PHOTON_DEPLOYMENT_MODE,
	VITE_PHOTON_TENANT_ID: process.env.VITE_PHOTON_TENANT_ID,
	VITE_PHOTON_TENANT_NAME: process.env.VITE_PHOTON_TENANT_NAME,
	VITE_PHOTON_WORKSPACE_ID: process.env.VITE_PHOTON_WORKSPACE_ID,
	VITE_PHOTON_WORKSPACE_NAME: process.env.VITE_PHOTON_WORKSPACE_NAME,
	VITE_PHOTON_APP_SERVER_BACKEND: process.env.VITE_PHOTON_APP_SERVER_BACKEND,
	VITE_PHOTON_API_BASE_URL: process.env.VITE_PHOTON_API_BASE_URL,
	VITE_PHOTON_ENGINE_PUSH_PATH: process.env.VITE_PHOTON_ENGINE_PUSH_PATH,
	VITE_PHOTON_ENGINE_PULL_PATH: process.env.VITE_PHOTON_ENGINE_PULL_PATH,
	VITE_PHOTON_SYNC_BACKEND: process.env.VITE_PHOTON_SYNC_BACKEND,
	VITE_PHOTON_SYNC_WS_URL: process.env.VITE_PHOTON_SYNC_WS_URL,
	VITE_PHOTON_SYNC_ENABLED: process.env.VITE_PHOTON_SYNC_ENABLED,
	VITE_PHOTON_RUNTIME_MODE: process.env.VITE_PHOTON_RUNTIME_MODE,
	VITE_PHOTON_AGENT_STREAM_URL: process.env.VITE_PHOTON_AGENT_STREAM_URL,
	VITE_PHOTON_AGENT_TOOL_RESULT_PATH:
		process.env.VITE_PHOTON_AGENT_TOOL_RESULT_PATH,
	COGNITO_CLIENT_ID: process.env.COGNITO_CLIENT_ID,
	COGNITO_CLIENT_SECRET: process.env.COGNITO_CLIENT_SECRET,
	COGNITO_DOMAIN: process.env.COGNITO_DOMAIN,
	COGNITO_ISSUER: process.env.COGNITO_ISSUER,
	COGNITO_REGION: process.env.COGNITO_REGION,
}

function getCloudflareRuntimeEnv(name: string): string | undefined {
	const runtimeGlobal = globalThis as RuntimeGlobal
	return runtimeGlobal.__env__?.[name] ?? runtimeGlobal.env?.[name]
}

export function getRuntimeEnv(name: string): string | undefined {
	const runtimeValue = getCloudflareRuntimeEnv(name)
	if (runtimeValue) {
		return runtimeValue
	}

	const processValue = process.env[name]
	if (processValue) {
		return processValue
	}

	return buildTimeEnv[name]
}
