query getCouponsForAdmin($limit: Int!, $offset: Int!, $activeOnly: Boolean) {
  coupons(limit: $limit, offset: $offset, activeOnly: $activeOnly) {
    data {
      ...CouponItemForAdmin
    }
    hasMore
  }
}

mutation createCouponForAdmin($input: CreateCouponInput!) {
  createCoupon(input: $input) {
    ...CouponItemForAdmin
  }
}

mutation disableCouponForAdmin($couponId: ID!) {
  disableCoupon(couponId: $couponId) {
    ...CouponItemForAdmin
  }
}

fragment CouponItemForAdmin on GqlCoupon {
  id
  code
  discountType
  discountValue
  currency
  exclusionGroup
  isActive
  createdAt
}
