export type SelectOption<T = string> = {
	label: string
	value: T
}

export const productBillingCycleOptions: SelectOption[] = [
	{ label: '月額', value: 'MONTHLY' },
	{ label: '年額', value: 'YEARLY' },
	{ label: '一回のみ', value: 'ONCE' },
]

export const productKindOptions: SelectOption[] = [
	{ label: 'プラン（ソフトウェア）', value: 'PLAN' },
	{ label: 'ハードウェア', value: 'PRODUCT' },
	{ label: 'オプション', value: 'OPTION' },
]

export const prefectureOptions: SelectOption[] = [
	{ value: '北海道', label: '北海道' },
	{ value: '青森県', label: '青森県' },
	{ value: '岩手県', label: '岩手県' },
	{ value: '宮城県', label: '宮城県' },
	{ value: '秋田県', label: '秋田県' },
	{ value: '山形県', label: '山形県' },
	{ value: '福島県', label: '福島県' },
	{ value: '茨城県', label: '茨城県' },
	{ value: '栃木県', label: '栃木県' },
	{ value: '群馬県', label: '群馬県' },
	{ value: '埼玉県', label: '埼玉県' },
	{ value: '千葉県', label: '千葉県' },
	{ value: '東京都', label: '東京都' },
	{ value: '神奈川県', label: '神奈川県' },
	{ value: '新潟県', label: '新潟県' },
	{ value: '富山県', label: '富山県' },
	{ value: '石川県', label: '石川県' },
	{ value: '福井県', label: '福井県' },
	{ value: '山梨県', label: '山梨県' },
	{ value: '長野県', label: '長野県' },
	{ value: '岐阜県', label: '岐阜県' },
	{ value: '静岡県', label: '静岡県' },
	{ value: '愛知県', label: '愛知県' },
	{ value: '三重県', label: '三重県' },
	{ value: '滋賀県', label: '滋賀県' },
	{ value: '京都府', label: '京都府' },
	{ value: '大阪府', label: '大阪府' },
	{ value: '兵庫県', label: '兵庫県' },
	{ value: '奈良県', label: '奈良県' },
	{ value: '和歌山県', label: '和歌山県' },
	{ value: '鳥取県', label: '鳥取県' },
	{ value: '島根県', label: '島根県' },
	{ value: '岡山県', label: '岡山県' },
	{ value: '広島県', label: '広島県' },
	{ value: '山口県', label: '山口県' },
	{ value: '徳島県', label: '徳島県' },
	{ value: '香川県', label: '香川県' },
	{ value: '愛媛県', label: '愛媛県' },
	{ value: '高知県', label: '高知県' },
	{ value: '福岡県', label: '福岡県' },
	{ value: '佐賀県', label: '佐賀県' },
	{ value: '長崎県', label: '長崎県' },
	{ value: '熊本県', label: '熊本県' },
	{ value: '大分県', label: '大分県' },
	{ value: '宮崎県', label: '宮崎県' },
	{ value: '鹿児島県', label: '鹿児島県' },
	{ value: '沖縄県', label: '沖縄県' },
]

export const industryOptions = [
	{ value: 'ACCOUNTING', label: '会計' },
	{ value: 'AIRLINES_AVIATION', label: '航空/航空宇宙' },
	{ value: 'ALTERNATIVE_DISPUTE_RESOLUTION', label: '代替紛争解決' },
	{ value: 'ALTERNATIVE_MEDICINE', label: '代替医療' },
	{ value: 'ANIMATION', label: 'アニメーション' },
	{ value: 'APPAREL_FASHION', label: 'アパレル/ファッション' },
	{ value: 'ARCHITECTURE_PLANNING', label: '建築/計画' },
	{ value: 'ARTS_AND_CRAFTS', label: 'アート/クラフト' },
	{ value: 'AUTOMOTIVE', label: '自動車' },
	{ value: 'AVIATION_AEROSPACE', label: '航空宇宙' },
	{ value: 'BANKING', label: '銀行' },
	{ value: 'BIOTECHNOLOGY', label: 'バイオテクノロジー' },
	{ value: 'BROADCAST_MEDIA', label: '放送/メディア' },
	{ value: 'BUILDING_MATERIALS', label: '建材' },
	{ value: 'BUSINESS_SUPPLIES_AND_EQUIPMENT', label: '事務用品/設備' },
	{ value: 'CAPITAL_MARKETS', label: '資本市場' },
	{ value: 'CHEMICALS', label: '化学' },
	{ value: 'CIVIC_SOCIAL_ORGANIZATION', label: '市民/社会組織' },
	{ value: 'CIVIL_ENGINEERING', label: '土木工学' },
	{ value: 'COMMERCIAL_REAL_ESTATE', label: '商業不動産' },
	{
		value: 'COMPUTER_NETWORK_SECURITY',
		label: 'コンピュータネットワーク/セキュリティ',
	},
	{ value: 'COMPUTER_GAMES', label: 'コンピューターゲーム' },
	{ value: 'COMPUTER_HARDWARE', label: 'コンピューターハードウェア' },
	{ value: 'COMPUTER_NETWORKING', label: 'コンピューターネットワーキング' },
	{ value: 'COMPUTER_SOFTWARE', label: 'コンピューターソフトウェア' },
	{ value: 'INTERNET', label: 'インターネット' },
	{ value: 'CONSTRUCTION', label: '建設' },
	{ value: 'CONSUMER_ELECTRONICS', label: '家電' },
	{ value: 'CONSUMER_GOODS', label: '消費財' },
	{ value: 'CONSUMER_SERVICES', label: '消費者サービス' },
	{ value: 'COSMETICS', label: '化粧品' },
	{ value: 'DAIRY', label: '乳製品' },
	{ value: 'DEFENSE_SPACE', label: '防衛/宇宙' },
	{ value: 'DESIGN', label: 'デザイン' },
	{ value: 'EDUCATION_MANAGEMENT', label: '教育/管理' },
	{ value: 'E_LEARNING', label: 'E-ラーニング' },
	{ value: 'ELECTRICAL_ELECTRONIC_MANUFACTURING', label: '電気/電子製造' },
	{ value: 'ENTERTAINMENT', label: 'エンターテイメント' },
	{ value: 'ENVIRONMENTAL_SERVICES', label: '環境サービス' },
	{ value: 'EVENTS_SERVICES', label: 'イベントサービス' },
	{ value: 'EXECUTIVE_OFFICE', label: '経営幹部' },
	{ value: 'FACILITIES_SERVICES', label: '施設サービス' },
	{ value: 'FARMING', label: '農業' },
	{ value: 'FINANCIAL_SERVICES', label: '金融サービス' },
	{ value: 'FINE_ART', label: 'ファインアート' },
	{ value: 'FISHERY', label: '漁業' },
	{ value: 'FOOD_BEVERAGES', label: '食品/飲料' },
	{ value: 'FOOD_PRODUCTION', label: '食品生産' },
	{ value: 'FUND_RAISING', label: '資金調達' },
	{ value: 'FURNITURE', label: '家具' },
	{ value: 'GAMBLING_CASINOS', label: 'ギャンブル/カジノ' },
	{ value: 'GLASS_CERAMICS_CONCRETE', label: 'ガラス/セラミック/コンクリート' },
	{ value: 'GOVERNMENT_ADMINISTRATION', label: '政府/行政' },
	{ value: 'GOVERNMENT_RELATIONS', label: '政府関係' },
	{ value: 'GRAPHIC_DESIGN', label: 'グラフィックデザイン' },
	{
		value: 'HEALTH_WELLNESS_AND_FITNESS',
		label: '健康/ウェルネス/フィットネス',
	},
	{ value: 'HIGHER_EDUCATION', label: '高等教育' },
	{ value: 'HOSPITAL_HEALTH_CARE', label: '病院/ヘルスケア' },
	{ value: 'HOSPITALITY', label: 'ホスピタリティ' },
	{ value: 'HUMAN_RESOURCES', label: '人事' },
	{ value: 'IMPORT_AND_EXPORT', label: '輸入/輸出' },
	{ value: 'INDIVIDUAL_FAMILY_SERVICES', label: '個人/家族サービス' },
	{ value: 'INDUSTRIAL_AUTOMATION', label: '産業自動化' },
	{ value: 'INFORMATION_SERVICES', label: '情報サービス' },
	{ value: 'INFORMATION_TECHNOLOGY_AND_SERVICES', label: '情報技術/サービス' },
	{ value: 'INSURANCE', label: '保険' },
	{ value: 'INTERNATIONAL_AFFAIRS', label: '国際関係' },
	{ value: 'INTERNATIONAL_TRADE_AND_DEVELOPMENT', label: '国際貿易/開発' },
	{ value: 'INVESTMENT_BANKING', label: '投資銀行' },
	{ value: 'INVESTMENT_MANAGEMENT', label: '投資管理' },
	{ value: 'JUDICIARY', label: '司法' },
	{ value: 'LAW_ENFORCEMENT', label: '法執行' },
	{ value: 'LAW_PRACTICE', label: '法務' },
	{ value: 'LEGAL_SERVICES', label: '法的サービス' },
	{ value: 'LEGISLATIVE_OFFICE', label: '立法' },
	{ value: 'LEISURE_TRAVEL_TOURISM', label: 'レジャー/旅行/観光' },
	{ value: 'LIBRARIES', label: '図書館' },
	{ value: 'LOGISTICS_AND_SUPPLY_CHAIN', label: '物流/サプライチェーン' },
	{ value: 'LUXURY_GOODS_JEWELRY', label: 'ラグジュアリーグッズ/ジュエリー' },
	{ value: 'MACHINERY', label: '機械' },
	{ value: 'MANAGEMENT_CONSULTING', label: '経営コンサルティング' },
	{ value: 'MARITIME', label: '海事' },
	{ value: 'MARKET_RESEARCH', label: '市場調査' },
	{ value: 'MARKETING_AND_ADVERTISING', label: 'マーケティング/広告' },
	{ value: 'MECHANICAL_OR_INDUSTRIAL_ENGINEERING', label: '機械/産業工学' },
	{ value: 'MEDIA_PRODUCTION', label: 'メディア制作' },
	{ value: 'MEDICAL_DEVICES', label: '医療機器' },
	{ value: 'MEDICAL_PRACTICE', label: '医療' },
	{ value: 'MENTAL_HEALTH_CARE', label: 'メンタルヘルスケア' },
	{ value: 'MILITARY', label: '軍事' },
	{ value: 'MINING_METALS', label: '鉱業/金属' },
	{ value: 'MOTION_PICTURES_AND_FILM', label: '映画' },
	{ value: 'MUSEUMS_AND_INSTITUTIONS', label: '博物館/施設' },
	{ value: 'MUSIC', label: '音楽' },
	{ value: 'NANOTECHNOLOGY', label: 'ナノテクノロジー' },
	{ value: 'NEWSPAPERS', label: '新聞' },
	{ value: 'NON_PROFIT_ORGANIZATION_MANAGEMENT', label: '非営利団体' },
	{ value: 'OIL_ENERGY', label: '石油/エネルギー' },
	{ value: 'ONLINE_MEDIA', label: 'オンラインメディア' },
	{ value: 'OUTSOURCING_OFFSHORING', label: '外部委託/海外' },
	{ value: 'PACKAGE_FREIGHT_DELIVERY', label: '荷物/貨物配送' },
	{ value: 'PACKAGING_AND_CONTAINERS', label: '包装/容器' },
	{ value: 'PAPER_FOREST_PRODUCTS', label: '紙/森林製品' },
	{ value: 'PERFORMING_ARTS', label: 'パフォーミングアート' },
	{ value: 'PHARMACEUTICALS', label: '製薬' },
	{ value: 'PHILANTHROPY', label: '慈善事業' },
	{ value: 'PHOTOGRAPHY', label: '写真' },
	{ value: 'PLASTICS', label: 'プラスチック' },
	{ value: 'POLITICAL_ORGANIZATION', label: '政治組織' },
	{ value: 'PRIMARY_SECONDARY_EDUCATION', label: '小中学校' },
	{ value: 'PRINTING', label: '印刷' },
	{
		value: 'PROFESSIONAL_TRAINING_COACHING',
		label: '専門トレーニング/コーチング',
	},
	{ value: 'PROGRAM_DEVELOPMENT', label: 'プログラム開発' },
	{ value: 'PUBLIC_POLICY', label: '公共政策' },
	{
		value: 'PUBLIC_RELATIONS_AND_COMMUNICATIONS',
		label: '広報/コミュニケーション',
	},
	{ value: 'PUBLIC_SAFETY', label: '公共安全' },
	{ value: 'PUBLISHING', label: '出版' },
	{ value: 'RAILROAD_MANUFACTURE', label: '鉄道製造' },
	{ value: 'RANCHING', label: '牧畜' },
	{ value: 'REAL_ESTATE', label: '不動産' },
	{
		value: 'RECREATIONAL_FACILITIES_AND_SERVICES',
		label: 'レクリエーション施設/サービス',
	},
	{ value: 'RELIGIOUS_INSTITUTIONS', label: '宗教機関' },
	{ value: 'RENEWABLES_ENVIRONMENT', label: '再生可能エネルギー/環境' },
	{ value: 'RESEARCH', label: '研究' },
	{ value: 'RESTAURANTS', label: 'レストラン' },
	{ value: 'RETAIL', label: '小売' },
	{ value: 'SECURITY_AND_INVESTIGATIONS', label: 'セキュリティ/調査' },
	{ value: 'SEMICONDUCTORS', label: '半導体' },
	{ value: 'SHIPBUILDING', label: '造船' },
	{ value: 'SPORTING_GOODS', label: 'スポーツ用品' },
	{ value: 'SPORTS', label: 'スポーツ' },
	{ value: 'STAFFING_AND_RECRUITING', label: 'スタッフィング/採用' },
	{ value: 'SUPERMARKETS', label: 'スーパーマーケット' },
	{ value: 'TELECOMMUNICATIONS', label: '通信' },
	{ value: 'TEXTILES', label: 'テキスタイル' },
	{ value: 'THINK_TANKS', label: 'シンクタンク' },
	{ value: 'TOBACCO', label: 'たばこ' },
	{ value: 'TRANSLATION_AND_LOCALIZATION', label: '翻訳/ローカライゼーション' },
	{ value: 'TRANSPORTATION_TRUCKING_RAILROAD', label: '運輸/トラック/鉄道' },
	{ value: 'UTILITIES', label: '公益事業' },
	{
		value: 'VENTURE_CAPITAL_PRIVATE_EQUITY',
		label: 'ベンチャーキャピタル/プライベートエクイティ',
	},
	{ value: 'VETERINARY', label: '獣医' },
	{ value: 'WAREHOUSING', label: '倉庫' },
	{ value: 'WHOLESALE', label: '卸売' },
	{ value: 'WINE_AND_SPIRITS', label: 'ワイン/スピリッツ' },
	{ value: 'WIRELESS', label: 'ワイヤレス' },
	{ value: 'WRITING_AND_EDITING', label: '執筆/編集' },
]
