import { Badge } from 'components/ui/badge'
import { Button } from 'components/ui/button'
import {
	Card,
	CardContent,
	CardDescription,
	CardFooter,
	CardHeader,
	CardTitle,
} from 'components/ui/card'
import {
	DropdownMenu,
	DropdownMenuCheckboxItem,
	DropdownMenuContent,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from 'components/ui/dropdown-menu'
import { EmptyState } from 'components/ui/page-shell'
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from 'components/ui/table'
import { Tabs, TabsContent, TabsList, TabsTrigger } from 'components/ui/tabs'
import { getServerModePrefix } from 'lib/mode'
import { FileIcon, ListFilterIcon, UploadCloudIcon } from 'lucide-react'
import type { Route } from 'next'
import Link from 'next/link'
import { BridgeRunDialog } from './bridge-run-dialog'

type ImportItemForImportsListFragment = {
	id: string
	name: string
	status: '有効' | '無効'
	createdAt: string
	sourceType?: string
	targetObject?: string
}

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lDGCzMX0Z5U
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export function ImportsList({
	data,
	errorMessage,
	tenantId,
	searchParams: { filter, query },
}: {
	data: ImportItemForImportsListFragment[]
	errorMessage?: string
	tenantId: string
	searchParams: {
		filter?: string
		query?: string
	}
}) {
	const normalizedQuery = query?.trim().toLowerCase()
	const activeData = data.filter(importItem => importItem.status === '有効')
	const inactiveData = data.filter(importItem => importItem.status === '無効')
	const visibleData = activeData.filter(importItem => {
		if (!normalizedQuery) return true
		return (
			importItem.name.toLowerCase().includes(normalizedQuery) ||
			importItem.sourceType?.toLowerCase().includes(normalizedQuery) ||
			importItem.targetObject?.toLowerCase().includes(normalizedQuery)
		)
	})

	return (
		<Tabs defaultValue={filter ?? 'active'}>
			<div className='flex items-center'>
				<TabsList className='hidden sm:flex' defaultValue={filter ?? 'active'}>
					<TabsTrigger value='active'>有効</TabsTrigger>
					<TabsTrigger value='inactive'>無効</TabsTrigger>
				</TabsList>
				<div className='ml-auto flex items-center gap-2'>
					<DropdownMenu>
						<DropdownMenuTrigger asChild>
							<Button className='h-8 gap-1' size='sm' variant='outline'>
								<ListFilterIcon className='h-3.5 w-3.5' />
								<span className='sr-only sm:not-sr-only sm:whitespace-nowrap'>
									フィルタ
								</span>
							</Button>
						</DropdownMenuTrigger>
						<DropdownMenuContent align='end'>
							<DropdownMenuLabel>フィルタリング</DropdownMenuLabel>
							<DropdownMenuSeparator />
							<DropdownMenuCheckboxItem checked>
								アクティブ
							</DropdownMenuCheckboxItem>
							<DropdownMenuCheckboxItem>下書き</DropdownMenuCheckboxItem>
							<DropdownMenuCheckboxItem>
								アーカイブ済み
							</DropdownMenuCheckboxItem>
						</DropdownMenuContent>
					</DropdownMenu>
					<Button className='h-8 gap-1' size='sm' variant='outline'>
						<FileIcon className='h-3.5 w-3.5' />
						<span className='sr-only sm:not-sr-only sm:whitespace-nowrap'>
							エクスポート
						</span>
					</Button>
					<Button className='h-8 gap-1' size='sm' asChild>
						<Link
							href={
								`${getServerModePrefix(tenantId)}/${tenantId}/imports/new` as Route
							}
						>
							<UploadCloudIcon className='h-3.5 w-3.5' />
							<span className='sr-only sm:not-sr-only sm:whitespace-nowrap'>
								Bridge Definition
							</span>
						</Link>
					</Button>
				</div>
			</div>
			<TabsContent value='active'>
				<Card x-chunk='dashboard-06-chunk-0'>
					<CardHeader>
						<CardTitle>Bridge Definitions</CardTitle>
						<CardDescription>
							外部sourceをFieldの業務世界モデルへ対応づける定義を管理します。
						</CardDescription>
					</CardHeader>
					<CardContent>
						{errorMessage ? (
							<EmptyState
								icon={<UploadCloudIcon />}
								title='Bridge Definitionを読み込めません'
								description={errorMessage}
							/>
						) : visibleData.length === 0 ? (
							<EmptyState
								icon={<UploadCloudIcon />}
								title='Bridge Definitionがありません'
								description='CSVやExcelのsource列をBridge Ontology Objectへ対応づけると、ここからプレビューとdraft作成を実行できます。'
								action={
									<Button size='sm' asChild>
										<Link
											href={
												`${getServerModePrefix(tenantId)}/${tenantId}/imports/new` as Route
											}
										>
											<UploadCloudIcon className='h-4 w-4 mr-1.5' />
											Bridge Definitionを作成する
										</Link>
									</Button>
								}
							/>
						) : (
							<Table>
								<TableHeader>
									<TableRow>
										<TableHead className='w-[50%]'>名前</TableHead>
										<TableHead className='w-[20%]'>ステータス</TableHead>
										<TableHead className='w-[20%]'>作成日時</TableHead>
										<TableHead className='w-[10%]'>
											<span className='sr-only'>Bridge Run</span>
										</TableHead>
									</TableRow>
								</TableHeader>
								<TableBody>
									{visibleData.map(importItem => (
										<TableRow key={importItem.id}>
											<TableCell className='font-medium'>
												{importItem.name}
												{importItem.sourceType && importItem.targetObject ? (
													<div className='text-muted-foreground text-xs'>
														{importItem.sourceType} -&gt;{' '}
														{importItem.targetObject}
													</div>
												) : null}
											</TableCell>
											<TableCell>
												<Badge variant='outline'>{importItem.status}</Badge>
											</TableCell>
											<TableCell>
												{new Date(importItem.createdAt).toLocaleString(
													'ja-JP',
													{
														year: 'numeric',
														month: '2-digit',
														day: '2-digit',
														hour: '2-digit',
														minute: '2-digit',
														hour12: true,
													},
												)}
											</TableCell>
											<TableCell>
												<BridgeRunDialog
													definitionId={importItem.id}
													definitionName={importItem.name}
													tenantId={tenantId}
												/>
											</TableCell>
										</TableRow>
									))}
								</TableBody>
							</Table>
						)}
					</CardContent>
					<CardFooter
						className={visibleData.length === 0 ? 'hidden' : undefined}
					>
						<div className='text-xs text-muted-foreground'>
							<strong>1-{visibleData.length}</strong> のうち、
							<strong>{visibleData.length}</strong>
							Bridge Definitionを表示しています
						</div>
					</CardFooter>
				</Card>
			</TabsContent>
			<TabsContent value='inactive'>
				<InactiveTab data={inactiveData} tenantId={tenantId} />
			</TabsContent>
		</Tabs>
	)
}

/**
 * 停止中のBridge Definitionを表示するタブ
 */
function InactiveTab({
	data,
	tenantId,
}: {
	data: ImportItemForImportsListFragment[]
	tenantId: string
}) {
	return (
		<Card x-chunk='dashboard-06-chunk-0'>
			<CardHeader>
				<CardTitle>停止中のBridge Definitions</CardTitle>
				<CardDescription>
					現在停止しているBridge Definitionを確認します。
				</CardDescription>
			</CardHeader>
			<CardContent>
				<Table>
					<TableHeader>
						<TableRow>
							<TableHead>名前</TableHead>
							<TableHead>ステータス</TableHead>
							<TableHead>作成日時</TableHead>
							<TableHead>
								<span className='sr-only'>Bridge Run</span>
							</TableHead>
						</TableRow>
					</TableHeader>
					<TableBody>
						{data.map(v => (
							<TableRow key={v.id}>
								<TableCell className='font-medium'>{v.name}</TableCell>
								<TableCell>
									<Badge variant='outline'>{v.status}</Badge>
								</TableCell>
								<TableCell>
									{new Date(v.createdAt).toLocaleString('ja-JP', {
										year: 'numeric',
										month: '2-digit',
										day: '2-digit',
										hour: '2-digit',
										minute: '2-digit',
										hour12: true,
									})}
								</TableCell>
								<TableCell>
									<BridgeRunDialog
										definitionId={v.id}
										definitionName={v.name}
										tenantId={tenantId}
									/>
								</TableCell>
							</TableRow>
						))}
					</TableBody>
				</Table>
			</CardContent>
			<CardFooter>
				<div className='text-xs text-muted-foreground'>
					<strong>1-{data.length}</strong> のうち、
					<strong>{data.length}</strong>
					Bridge Definitionを表示しています
				</div>
			</CardFooter>
		</Card>
	)
}
