import { Badge } from 'components/ui/badge'
import { Button } from 'components/ui/button'
import {
	Card,
	CardContent,
	CardDescription,
	CardFooter,
	CardHeader,
	CardTitle,
} from 'components/ui/card'
import { Input } from 'components/ui/input'
import { Label } from 'components/ui/label'
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from 'components/ui/select'
import { ChevronLeftIcon } from 'lucide-react'
import type { Route } from 'next'
import Link from 'next/link'
import { FileUploadButton } from './file-upload-button'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fBg7KwSBUl3
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export function NewImport({
	action,
	backLink,
}: {
	action: (formData: FormData) => void | Promise<void>
	backLink: Route
}) {
	return (
		<main className='grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8'>
			<form
				action={action}
				className='mx-auto grid max-w-[59rem] flex-1 auto-rows-max gap-4'
			>
				<div className='flex items-center gap-4'>
					<Button className='h-7 w-7' size='icon' variant='outline' asChild>
						<Link href={backLink}>
							<ChevronLeftIcon className='h-4 w-4' />
							<span className='sr-only'>戻る</span>
						</Link>
					</Button>
					<h1 className='flex-1 shrink-0 whitespace-nowrap text-xl font-semibold tracking-tight sm:grow-0'>
						新規Bridge Definition
					</h1>
					<Badge className='ml-auto sm:ml-0' variant='outline'>
						AIP-ready
					</Badge>
					<div className='hidden items-center gap-2 md:ml-auto md:flex'>
						<Button size='sm' variant='outline' asChild>
							<Link href={backLink}>破棄</Link>
						</Button>
						<Button size='sm'>Definitionを保存</Button>
					</div>
				</div>
				<div className='grid gap-4 md:grid-cols-[1fr_250px] lg:grid-cols-3 lg:gap-8'>
					<div className='grid auto-rows-max items-start gap-4 lg:col-span-2 lg:gap-8'>
						<Card x-chunk='dashboard-07-chunk-0'>
							<CardHeader>
								<CardTitle>Bridge Definition詳細</CardTitle>
								<CardDescription>
									外部sourceのサンプルを与え、Bridge Ontology
									Objectへのmapping候補を作成します。
								</CardDescription>
							</CardHeader>
							<CardContent>
								<div className='grid gap-6'>
									<div className='grid gap-3'>
										<Label htmlFor='name'>Definition名</Label>
										<Input
											className='w-full'
											id='name'
											name='name'
											required
											type='text'
											placeholder='POS売上CSV -> SalesLedgerDraft'
										/>
									</div>
									<div className='grid gap-3'>
										<Label htmlFor='targetObject'>Bridge Ontology Object</Label>
										<Select defaultValue='salesLedgerDraft' name='targetObject'>
											<SelectTrigger
												aria-label='対象objectを選択'
												id='targetObject'
											>
												<SelectValue placeholder='対象objectを選択' />
											</SelectTrigger>
											<SelectContent>
												<SelectItem value='salesLedgerDraft'>
													SalesLedgerDraft
												</SelectItem>
												<SelectItem value='purchaseLedgerDraft'>
													PurchaseLedgerDraft
												</SelectItem>
												<SelectItem value='bankTransaction'>
													BankTransaction
												</SelectItem>
											</SelectContent>
										</Select>
									</div>
									<div className='grid gap-3'>
										<Label htmlFor='description'>説明</Label>
										<Input
											className='w-full'
											id='description'
											name='description'
											type='text'
											placeholder='SBI銀行CSVやPOS日次売上CSVなど'
										/>
									</div>
									<div className='grid gap-3'>
										<Label htmlFor='sampleFile'>CSVサンプルファイル</Label>
										<FileUploadButton />
										<p className="text-zinc-500 text-sm font-normal font-['Inter'] leading-tight">
											実際のCSVサンプルからheader、型、サンプル値を検出し、LLMを含むmapping候補を作成します。
										</p>
									</div>
								</div>
							</CardContent>
						</Card>
					</div>

					<div className='grid auto-rows-max items-start gap-4 lg:gap-8'>
						<Card x-chunk='dashboard-07-chunk-3'>
							<CardHeader>
								<CardTitle>Definitionステータス</CardTitle>
							</CardHeader>
							<CardContent>
								<div className='grid gap-6'>
									<div className='grid gap-3'>
										<Label htmlFor='status'>ステータス</Label>
										<Select defaultValue='active'>
											<SelectTrigger aria-label='ステータスを選択' id='status'>
												<SelectValue placeholder='ステータスを選択' />
											</SelectTrigger>
											<SelectContent>
												<SelectItem value='active'>有効</SelectItem>
												<SelectItem value='inactive'>無効</SelectItem>
											</SelectContent>
										</Select>
									</div>
								</div>
							</CardContent>
						</Card>
					</div>
				</div>
				<div className='flex items-center justify-center gap-2 md:hidden'>
					<Button size='sm' variant='outline' asChild>
						<Link href={backLink}>破棄</Link>
					</Button>
					<Button size='sm'>Definitionを保存</Button>
				</div>
			</form>
		</main>
	)
}
